apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: productpage
  replicas: 2
  template:
    metadata:
      labels:
        app: productpage
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: details
        image: iad.ocir.io/idmaqhrbiuyo/product:v0.1
        ports:
        - containerPort: 3000